sudo: false
language: rust
rust:
- beta
- nightly
matrix:
  include:
    - script: '"$TRAVIS_BUILD_DIR/test-runtime" --no-default-features'
      env:
        - FILEWATCH=false
    - script: '"$TRAVIS_BUILD_DIR/test-runtime"'
      env:
        - FILEWATCH=true
