sudo: false
language: rust
script:
  - cd "$TRAVIS_BUILD_DIR/plugin-generator" && cargo run --release
  - cd "$TRAVIS_BUILD_DIR/zaldinar-runtime" && [[ "$BUILD_FILEWATCH" == true ]] && cargo build || cargo build --no-default-features
cache:
  directories:
    # Cache compiled dependencies
    - zaldinar-runtime/target/
    - plugin-generator/target/

rust:
  - 1.0.0-beta
  - nightly
env:
  - BUILD_FILEWATCH=true
  - BUILD_FILEWATCH=false
matrix:
  exclude:
    - rust: 1.0.0-beta
      env: BUILD_FILEWATCH=true
