sudo: false
language: rust
rust: nightly
script:
  - cd "$TRAVIS_BUILD_DIR/plugin-generator" && cargo run --release
  - cd "$TRAVIS_BUILD_DIR/zaldinar-runtime" && cargo build
cache:
  directories:
    # Cache compiled dependencies
    - zaldinar-runtime/target/
    - plugin-generator/target/
