#!/bin/zsh

ZALDINAR_PATH="$PWD"

cd "${ZALDINAR_PATH}/plugin-generator" &&
cargo run --release &&
cd "${ZALDINAR_PATH}/build-out/cumulative-crate" &&
if [[ ! -z "$@" ]]; then
    cargo build "$@"
else
    cargo build
fi
