[package]

name = "zaldinar"
version = "0.0.1"
authors = ["Dabo Ross <daboross@daboross.net>"]

[dependencies]
chrono = "~0.1.3"

[dependencies.fern]
git = 'https://github.com/daboross/fern-rs.git'

[dependencies.fern_macros]
git = 'https://github.com/daboross/fern-macros-rs.git'
