#!/bin/bash

ZALDINAR_PATH="$(dirname "$([[ $0 = /* ]] && echo "$0" || echo "$PWD/${0#./}")")"

cd "${ZALDINAR_PATH}/plugin-generator" &&
cargo run --release &&
cd "${ZALDINAR_PATH}/zaldinar-runtime" &&
if [[ ! -z "$@" ]]; then
    cargo test "$@"
else
    cargo test
fi
