[package]

name = "zaldinar-core"
version = "0.1.1-dev"
authors = ["Dabo Ross <daboross@daboross.net>"]

[dependencies]
regex = "0.1.*"
rustc-serialize = "0.3.*"
log = "0.3.*"
fern = "0.3.*"

[dependencies.zaldinar-irclib]
path = "../zaldinar-irclib"
