[package]
name = "zaldinar-core"
version = "0.1.1-dev"
authors = ["David Ross <daboross@daboross.net>"]

[dependencies]
regex = "0.2"
rustc-serialize = "0.3"
log = "0.3"
throw = "0.1"

[dependencies.zaldinar-irclib]
path = "../zaldinar-irclib"
