[package]

name = "zaldinar-core"
version = "0.0.1"
authors = ["Dabo Ross <daboross@daboross.net>"]

[dependencies]
regex = "0.1.14"
regex_macros = "0.1.8"
rustc-serialize = "0.3.1"
log = "0.2.5"
fern = "0.2.0"

[dependencies.zaldinar-irclib]
path = "../zaldinar-irclib"
