[package]
name = "zaldinar-core"
version = "0.1.1-dev"
authors = ["David Ross <daboross@daboross.net>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
regex = "0.2"
log = "0.3"
throw = "0.1"

[dependencies.zaldinar-irclib]
path = "../zaldinar-irclib"
