[package]

name = "zaldinar"
version = "0.1.1-dev"
authors = ["Dabo Ross <daboross@daboross.net>"]

[dependencies]
regex = "0.1.14"
regex_macros = "0.1.8"
rustc-serialize = "0.3.1"
chrono = "0.2.1"
getopts = "0.2.3"
inotify = "0.1.8"
log = "0.2.5"
fern = "0.2.0"

[dependencies.libc]
version = "0.1.3"
optional = true

[dependencies.zaldinar-irclib]
path = "../zaldinar-irclib"

[dependencies.zaldinar-core]
path = "../zaldinar-core"

[dependencies.generated-plugins-crate]
path = "../build-out/cumulative-crate"

[features]
default = ["binary-filewatch"]

binary-filewatch = ["libc"]

[profile.release]
lto = true
